### ISSUE TITLE
USB Keyboard nonfunctional

### ISSUE THREAD

**Issue by jdude104** [dhansel/VersaTerm#15]
Attempting to reproduce the schematic on a protoboard, and for some reason USB keyboard will not work no matter what I do. I have tried both an OTG adapter directly into the Pico's micro-usb, and a dedicated port wired as such:

![Image](https://github.com/user-attachments/assets/a22cd161-ff9c-498c-b2a7-900e3ef67c9f)

HDMI works fine, as do the RESET and DEFAULT buttons, I do not have PS/2 or VGA connected. If I connect it to my computer over serial, I can enter keys that way, but obviously this is not ideal. I have attempted building the code myself from source, and that did not solve the issue.

**Comment by dhansel** [comment]
What kind of USB keyboard are you connecting? I have found that the version of TinyUSB that VersaTerm currently uses has trouble with some USB hubs - and therefore also with USB keyboards that have integrated hubs. Those issues are resolved in later versions of TinyUSB.

So if you are using some kind of more fancy keyboard (with built-in mouse support or a USB port to plug a mouse into or other extra features) that may be it. If you have one, try a very simple USB keyboard.

Since you have already re-built from source, another thing you can try is to follow my instructions [here](https://github.com/dhansel/VersaTerm/tree/main/software#tinyusb-updates) to update TinyUSB to the latest version. That should fix the USB hub issues.

If that doesn't help then double-check that your TP2/TP3 connections are correct (not accidentally reversed) and that the 5V/GND connections are correct.

Finally, some keyboards can draw a significant amount of power. Make sure that the power supply you are using is up to the task. You could measure the voltage across the 5V/GND on the keyboard while everything is turned on and the keyboard is connected. It shouldn't be too far off from 5V.

**Comment by dhansel** [comment]
I just updated the VersaTerm.uf2 file using the latest TinyUSB version. This one works with the USB hubs I have.

**Comment by jdude104** [comment]
Voltage is sitting at 5.2V and somewhere about 3-4mA. I verified by splitting a different USB cable that I have the data wires the correct way around and continuity checked to the TP2 and TP3 points. Keyboard is a Dell keyboard that would come with an office computer. New update does not seem to have fixed it, keyboard status lights still not turning on. Would it also failing with a simple OTG adapter plugged directly into the pico indicate anything?

**Comment by jdude104** [comment]
Update: If I instead flash the pico with https://github.com/HisashiKato/RunCPM_Pico_DVI_USB_Keyboard, changing the HDMI pins to match the versaterm schematic, the keyboard does function properly, just not when flashed with versaterm

**Comment by jdude104** [comment]
Sorry for the delay been a bit busy. The keyboards I've tested but haven't worked include:
Alienware Sk-8165
Dell sk-8115
Logitech G105
Dell KB216d
